### ISSUE TITLE
Indlæsning af miner og struct array til minerne

### ISSUE THREAD

**Issue by e-mtc** [e-mtc/P1#4]
En funktion læser x- og y-koordinater for minerne ind i et struct array til minerne. Hver struct variabel indeholder to unsigned int felter til koordinatsættet. 

Minerne skrives til et struct array som er en input/output parameter til funktionen.

**Comment by e-mtc** [comment]
hvis det er unsigned int skal man huske at nogle beregner bliver lidt mærkelig og man bliver nødt til at typecast

**Comment by Zhdun12** [comment]
Kan du give eksempler?
